version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "angularjs",
    "angular"
  ]
  environment = [
    "nodejs",
    "browser",
    "mongo",
    "jquery"
  ]

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"