version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "angularjs",
    "angular",
    "vue",
    "react"
  ]
  environment = [
    "nodejs",
    "browser",
    "mongo",
    "jquery"
  ]

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"