version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "angular",
    "vue",
    "angularjs"
  ]
  environment = [
    "browser",
    "nodejs",
    "jquery",
    "mongo"
  ]

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"